services:
  - type: web_service
    name: mycontacts-backend
    env: node
    plan: free
    root: backend
    # Install server deps, then build the frontend so static files are available
    buildCommand: npm install && cd ..\frontend && npm install && npm run build
    startCommand: npm start

  - type: static_site
    name: mycontacts-frontend
    env: static
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
